import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { AdminProvider } from "@/context/AdminContext";
import { ToastProvider } from "@/context/ToastContext";
import PageWrapper from "@/components/PageWrapper";
import Navbar from "@/components/Navbar";
import ToastContainer from "@/components/ToastContainer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ToastProvider>
            <AdminProvider>
              <Navbar />
              <ToastContainer />
              <div className="pt-20">
                <PageWrapper>{children}</PageWrapper>
              </div>
            </AdminProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
